/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yi_java3st_1team;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
